### ISSUE TITLE
🎉 Supported Notion Block Types Progress

### ISSUE THREAD

**Issue by anonymousRecords** [notionpresso/react#55]
## For New Contributors

- If there's a Notion block type you'd like to work on, please leave a comment on this issue, and we'll assign it to you.
- Once a 🎉 emoji appears on your comment, it means the assignment is complete, and you can start working on it!
- If no progress is made within **3 days** after the assignment, the block type may be reassigned to someone else. If you need more time, please let us know in the comments.
- If feedback is not incorporated within **1 week** after the PR review, the task may also be reassigned.
- While we’ll do our best to keep things updated quickly, please check the current PRs and issues regularly.
- Discussions regarding implementation will take place in the PR or issue threads.

## Supported Notion Block Types
- [x] Paragraph (`paragraph` ) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/2
- [x] Heading 1  (`heading_1` ) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/2
- [x] Heading 2  (`heading_2` ) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/2
- [x] Heading 3  (`heading_3` ) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/2
- [x] Bulleted List Item (`bulleted_list_item`) @anonymousRecords https://github.com/meursyphus/react-notion-custom/pull/13
- [x] Numbered List Item (`numbered_list_item`) @myjeong19 https://github.com/meursyphus/react-notion-custom/pull/28
- [x] To-do (`to_do` ) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/56
- [x] Toggle (`toggle`) @myjeong19 https://github.com/meursyphus/react-notion-custom/pull/9
- [x] Quote (`quote`) @myjeong19 https://github.com/meursyphus/react-notion-custom/pull/31
- [x] Callout (`callout`) @kimfield98 https://github.com/meursyphus/react-notion-custom/pull/30
- [x] Equation (`equation`) @p-iknow https://github.com/meursyphus/react-notion-custom/pull/25
- [x] Code (`code`) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/50
- [x] Image (`image`) @myjeong19 https://github.com/notionpresso/react/pull/51
- [x] Video (`video` ) @anonymousRecords https://github.com/meursyphus/react-notion-custom/pull/37
- [ ] Bookmark (`bookmark`) 
- [x] Divider (`divider`) @anonymousRecords https://github.com/meursyphus/react-notion-custom/pull/32
- [x] Table (`table`)@myjeong19 #79 
- [x] Table Row (`table_row`) @myjeong19 #79 
- [x] Column (`column`) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/49
- [x] Column List (`column_list`) @Moon-DaeSeung https://github.com/meursyphus/react-notion-custom/pull/49
- [ ] Audio (`audio`) https://github.com/meursyphus/react-notion-custom/issues/44
- [ ] Synced Block (`synced_block`) https://github.com/meursyphus/react-notion-custom/issues/59
- [ ] Table Of Contents (`table_of_contents`) https://github.com/meursyphus/react-notion-custom/issues/60
- [ ] Embed (`embed`) https://github.com/meursyphus/react-notion-custom/issues/61
- [ ] Figma (`figma`) https://github.com/meursyphus/react-notion-custom/issues/62
- [ ] Google Maps (`maps` ) https://github.com/meursyphus/react-notion-custom/issues/63
- [ ] Google Drive (`drive`) https://github.com/meursyphus/react-notion-custom/issues/64
- [ ] Tweet (`tweet`) https://github.com/meursyphus/react-notion-custom/issues/65
- [ ] PDF (`pdf`) https://github.com/meursyphus/react-notion-custom/issues/66
- [ ] File (`file`) https://github.com/meursyphus/react-notion-custom/issues/67
- [ ] Link (`text` (inline)) https://github.com/meursyphus/react-notion-custom/issues/68
- [ ] Page Link (`page`) https://github.com/meursyphus/react-notion-custom/issues/69
- [ ] External Page Link (`text` (inline) ) https://github.com/meursyphus/react-notion-custom/issues/70

Note: The following items are planned to be provided as different types (e.g., database) in the future and are not considered Notion Block Types:
- Collections (`collections`) https://github.com/meursyphus/react-notion-custom/issues/71
- Collection View (`collection_view`) https://github.com/meursyphus/react-notion-custom/issues/72
- Collection View Table (`collection_view_table`) https://github.com/meursyphus/react-notion-custom/issues/73
- Collection View Board (`collection_view_board`) https://github.com/meursyphus/react-notion-custom/issues/74
- Collection View List (`collection_view_list`) https://github.com/meursyphus/react-notion-custom/issues/75
- Collection View Calendar (`collection_view_calendar`) https://github.com/meursyphus/react-notion-custom/issues/76
- Collection View Page (`collection_view_page`) https://github.com/meursyphus/react-notion-custom/issues/77
